#!/bin/bash
#
sudo apt-get -y install apache2

#sudo vi /etc/apache2/apache2.conf

#enable user dirs
sudo a2enmod userdir

sudo service apache2 restart

apachetcl -v
# Now you should be able to browse to it and see it.
echo "PHP must also be installed ..."

sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
echo "deb https://packages.sury.org/php/ stretch main" | sudo tee /etc/apt/sources.list.d/php.list

cat /etc/apt/sources.list{,.d/*.list}

sudo apt-get update

sudo apt install -y php7.4 php7.4-common php7.4-curl php7.4-json php7.4-mysql php7.4-mbstring php7.4-zip 
php -v

sudo a2enmod php7.4

echo "Please update apache2.conf to allow php in userdir"

#sudo vi /etc/apache2/apache2.conf

# add in the following:
#<IfModule mod_userdir.c>
#        <Directory /home/adelaide/public_html>
#            php_admin_value engine On
#        </Directory>
#</IfModule>


#Now you can go to squiffy/~adelaide
