#!/bin/bash
#
sudo apt-get -y install apache2

#sudo vi /etc/apache2/apache2.conf

#enable user dirs
sudo a2enmod userdir

sudo service apache2 restart

apachetcl -v
# Now you should be able to browse to it and see it.
echo "PHP must also be installed ..."

echo "Please update apache2.conf to allow php in userdir"

#sudo vi /etc/apache2/apache2.conf

# add in the following:
#<IfModule mod_userdir.c>
#        <Directory /home/johnsmith/public_html>
#            php_admin_value engine On
#        </Directory>
#</IfModule>


#Now you can go to raspberryPi/~johnsmith
