#!/bin/bash
#NOTE the official lshell repo has two major security flaws. It is no longer being updated.
# It is version 0.9.8 from 2016.  Do not use it. 
# The following version has fixed the security flaws.

wget https://github.com/omega8cc/lshell/archive/refs/heads/master-om8.zip
unzip master-om8.zip
cd *om8
sudo python setup.py install --no-compile --install-scripts=/usr/bin/

# create users and groups
sudo adduser k32qz56
sudo groupadd lshellg
sudo usermod -aG lshellg k32qz56
sudo usermod -aG users k32qz56
sudo chsh -s /usr/bin/lshell k32qz56

# setup log, however LOGROTATE is not doing anything to it.
sudo mkdir /var/log/lshell
sudo chown :lshellg /var/log/lshell
sudo chmod 770 /var/log/lshell


echo "Please 'sudo vi /etc/lshell.conf' and make the following changes:"
echo "allowed         : ['ls','echo','ll','uname']"
echo "overssh         : ['uname']"
echo "strict          : 1"
