#!/bin/bash

# Script: RUN_INSTALL_PART2

#***************************************************************
#* This is a list of useful scripts for setting up a new RPi.  *
#* Uncomment/Comment the ones you want.                        *
#* Anything that requires user input or rebooting is labeled   *
#***************************************************************

# Part 2 continues from part 1, assuming that you've created a new superuser and want to delete the user pi.

if [ "$(whoami)" != "pi" ]; then
	w
	sudo -l
	groups
    echo "If running GUI then you have to make sure that that is logged off too before deleting PI user."
	echo "Do you want to delete user 'pi'?"
	read answer
	if [ $answer == "y" ] || [ $answer == "Y" ]; then
		sudo deluser pi
	fi
fi
#================================================================================
#   ------------ commands that pertain to current user ----------------
#================================================================================
# install pinout package and command

./install_pinout

#================================================================================
# fixup bashrc (and .profile). Change prompt, add alias, history size ...

./install_bashrc

#================================================================================
# install Vim plugins and .vimrc settings (and MC and Byobu settings)
# The files are in this repo.

./config_vim

#================================================================================
#   -------- commands that require care or are only for special use ---------
#================================================================================
# Configures sshd_conf, adds public_key
# EXTRA CONFIGURATION REQUIRED: check the script. 
#	Requires you to manually copy public key and test it before you reboot.
#	use ssh-copy-id
# REBOOT REQUIRED
echo -e "\n*** Warning: changing port and disabling password authentication. This may lock you out of the system after a reboot. ***"

./install_sshd

#================================================================================
# Installs fail2ban
# This is only needed on the access controller RPi.
# EXTRA CONFIGURATION REQUIRED: check the script. 
#	Some of the files created my not work.
#	jail.conf needs modifying

#./install_fail2ban

#================================================================================
# Installs LSHELL - for a very specific user. 
# This is only needed on the access controller RPi.

#./install_lshell


echo "**********************************************************************"
echo "Install script complete!"
echo "**********************************************************************"
